### ISSUE TITLE
Error on Ubuntu - /usr/sbin/mysqld error while loading libraries libaio.so.1 (with solution)

### ISSUE THREAD

**Issue by sebastientaggart** [aptalca/docker-zoneminder#13]
On Ubuntu, with apparmor enabled, I was getting these errors when attempting to run the container:

```
starting services
/usr/sbin/mysqld: error while loading shared libraries: libaio.so.1: cannot open shared object file: Permission denied
 * Starting MySQL database server mysqld
/usr/sbin/mysqld: error while loading shared libraries: libaio.so.1: cannot open shared object file: Permission denied
   ...fail!
```

This stops the rest of the container startup steps due to DB errors.  This is what fixed it for me:

`sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/`
`sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld`

This also disables apparmor for mysql on the host system though.

**Comment by aptalca** [comment]
This was a docker issue about a year ago, affecting many containers with mysql and privileged mode. At the time there was nothing I could do to fix it and the only solution was to disable apparmor. Not sure if anything's changed since.

You can try running it without the --privileged=true and see if it works (I honestly can't remember why I added the privileged mode)

**Comment by sebastientaggart** [comment]
For what it's worth I am running privileged=true but I still had to disable apparmor. I posted this ticket just to share the information, I agree that there's nothing you can do to fix this from the container side.
